=== Stormteller/KNU-programming-tasks/Year 3/Semester 1/Programming/XML Parsers/Candies.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="CandyNS"
        xmlns="CandyNS"
        elementFormDefault="qualified">

    <xs:element name="Candy">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="candy" type="Candy" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="name">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:simpleType name="energy">
        <xs:restriction base="xs:float" />
    </xs:simpleType>

    <xs:simpleType name="caramel">
        <xs:restriction base="xs:boolean" />
    </xs:simpleType>

    <xs:simpleType name="filling">
        <xs:restriction base="xs:boolean" />
    </xs:simpleType>

    <xs:simpleType name="chocolate">
        <xs:restriction base="xs:boolean" />
    </xs:simpleType>

    <xs:simpleType name="water">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="sugar">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="fructose">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="vanillin">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="protein">
        <xs:restriction base="xs:float" />
    </xs:simpleType>

    <xs:simpleType name="fats">
        <xs:restriction base="xs:float" />
    </xs:simpleType>

    <xs:simpleType name="carbohydrates">
        <xs:restriction base="xs:float" />
    </xs:simpleType>

    <xs:simpleType name="production">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="Candy">
        <xs:sequence>
            <xs:element name="Name" type="name"></xs:element>
            <xs:element name="Energy" type="energy"></xs:element>
            <xs:element name="Type">
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="Caramel" type="caramel"></xs:element>
                        <xs:element name="Filling" type="filling"></xs:element>
                        <xs:element name="Chocolate" type="chocolate"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Ingredients">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Water" type="water"></xs:element>
                        <xs:element name="Sugar" type="sugar"></xs:element>
                        <xs:element name="Fructose" type="fructose"></xs:element>
                        <xs:element name="Vanillin" type="vanillin"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Value">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Protein" type="protein"></xs:element>
                        <xs:element name="Fats" type="fats"></xs:element>
                        <xs:element name="Carbohydrates" type="carbohydrates"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Production" type = "production"></xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

</xs:schema>

=== Stormteller/KNU-programming-tasks/Year 3/Semester 1/Programming/XML Parsers/Candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<Candy xmlns="CandyNS"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="CandyNS Candies.xsd">
    <candies>
        <candy id="kor0">
            <Name>Korovka2</Name>
            <Energy>20</Energy>
            <Type>
                <Caramel>true</Caramel>
                <Filling>true</Filling>
                <Chocolate>false</Chocolate>
            </Type>
            <Ingredients>
                <Water>100</Water>
                <Sugar>50</Sugar>
                <Fructose>50</Fructose>
                <Vanillin>20</Vanillin>
            </Ingredients>
            <Value>
                <Protein>2</Protein>
                <Fats>5</Fats>
                <Carbohydrates>20</Carbohydrates>
            </Value>
            <Production>Roshen</Production>
        </candy>
        <candy id="kor1">
            <Name>Korovka1</Name>
            <Energy>1</Energy>
            <Type>
                <Caramel>true</Caramel>
                <Filling>true</Filling>
                <Chocolate>false</Chocolate>
            </Type>
            <Ingredients>
                <Water>100</Water>
                <Sugar>50</Sugar>
                <Fructose>50</Fructose>
                <Vanillin>20</Vanillin>
            </Ingredients>
            <Value>
                <Protein>2</Protein>
                <Fats>5</Fats>
                <Carbohydrates>20</Carbohydrates>
            </Value>
            <Production>Roshen</Production>
        </candy>
        <candy id="kor">
            <Name>Korovka</Name>
            <Energy>10</Energy>
            <Type>
                <Caramel>true</Caramel>
                <Filling>true</Filling>
                <Chocolate>false</Chocolate>
            </Type>
            <Ingredients>
                <Water>100</Water>
                <Sugar>50</Sugar>
                <Fructose>50</Fructose>
                <Vanillin>20</Vanillin>
            </Ingredients>
            <Value>
                <Protein>2</Protein>
                <Fats>5</Fats>
                <Carbohydrates>20</Carbohydrates>
            </Value>
            <Production>Roshen</Production>
        </candy>
        <candy id="nuts">
            <Name>CandyNuts</Name>
            <Energy>8</Energy>
            <Type>
                <Caramel>true</Caramel>
                <Filling>true</Filling>
                <Chocolate>true</Chocolate>
            </Type>
            <Ingredients>
                <Water>80</Water>
                <Sugar>60</Sugar>
                <Fructose>80</Fructose>
                <Vanillin>40</Vanillin>
            </Ingredients>
            <Value>
                <Protein>5</Protein>
                <Fats>9</Fats>
                <Carbohydrates>40</Carbohydrates>
            </Value>
            <Production>Roshen</Production>
        </candy>
    </candies>
</Candy>
